models.py
from dataclasses import dataclass, field
from datetime import date, datetime

@dataclass
class Todo:
    _id: str
    title: str
    description: str
    created_at: datetime = datetime.now()
    due_date: datetime = None
    # created_at: date = datetime.now()
    # due_date: date = None

@dataclass
class User:
    _id: str
    email: str
    password: str
    todos: list[str] = field(default_factory=list)

forms.py
from flask_wtf import FlaskForm
from datetime import date, datetime
import bson
from wtforms import (
    # IntegerField,
    StringField,
    TextAreaField,
    SubmitField,
    DateTimeField,
    DateField,
    PasswordField
)

from wtforms.validators import (
    InputRequired,
    DataRequired,
    Email,
    EqualTo,
    Length,
    ValidationError
    # NumberRange
)

class LoginForm(FlaskForm):
    email = StringField("Email", validators=[
        InputRequired(),
        Email()
    ])
    password = PasswordField("Password", validators=[
        InputRequired(),
    ])
    submit = SubmitField("Login")

class RegisterForm(FlaskForm):
    email = StringField("Email", validators=[
        InputRequired(),
        Email(),
    ])
    password = PasswordField("Password", validators=[
        InputRequired(),
        Length(min=4,max=20, message="Your password must be between 4 to 20 charecters long.")
    ])
    confirm_password = PasswordField("Confirm Password", validators=[
        InputRequired(),
        EqualTo("password",message="This password did not match the one  in the password field.")
    ])

    submit = SubmitField("Register")


def date_validation(form,field):
    submitted_date = field.data
    if submitted_date is None:
        raise ValidationError('Date field cannot be empty.')
    
    current_date = datetime.now()
    if submitted_date < current_date:
        raise ValidationError('Date cannot be in the past.')

def modifyIput(form, field):
    _date = field.data
    # print(_date)
    # print(type(_date))
    # _date = datetime.strptime(_date, '%Y-%m-%d')
    field.data = _date.isoformat()
    print(field.data)

    
class TodoForm(FlaskForm):
    title = StringField("Title", validators=[
        InputRequired(), 
        Length(min=3,max=50)
    ])
    description = TextAreaField("Description", validators=[
        InputRequired(),
        Length(min=3,max=500)
    ])
    due_date = DateTimeField("Due Date", format='%d-%m-%YT%H:%M', validators=[
        # DataRequired(),
        InputRequired(),
        # date_validation
        # modifyIput
    ])
    submit = SubmitField("Add Todo") 


    

__init__.py
import os
from flask import Flask, session
from dotenv import load_dotenv
from pymongo import MongoClient

from todoApp.routes import pages

load_dotenv()


# def create_app():
app = Flask(__name__)
# app.config["MONGODB_URI"] = os.environ.get("MONGODB_URI")
app.config["MONGODB_URI"] = "mongodb://localhost:27017/todo-app-flask"
app.config["SECRET_KEY"] = os.environ.get(
    "SECRET_KEY", "pf9Wkove4IKEAXvy-cQkeDPhv9Cb3Ag-wyJILbq_dFw"
)
app.db = MongoClient(app.config["MONGODB_URI"]).get_default_database()

app.register_blueprint(pages)
# session["theme"]="light"
# return app

if __name__ == '__main__':
    app.run(debug=True)

routes.py
import time
from flask import (
    Blueprint, 
    render_template,
    current_app,
    flash,
    redirect,
    session,
    url_for,
    request
)
import functools
import uuid
import datetime
from dataclasses import asdict

from todoApp.forms import LoginForm, RegisterForm, TodoForm
from todoApp.models import User, Todo
from passlib.hash import pbkdf2_sha256


pages = Blueprint(
    "pages", __name__, template_folder="templates", static_folder="static"
)


def login_required(route):
    @functools.wraps(route)
    def route_wrapper(*args, **kwargs):
        if session.get("email") is None:
            return redirect(url_for(".login"))
        return route(*args, **kwargs)
    return route_wrapper


@pages.route("/")
@login_required
def index():
    user_data = current_app.db.user.find_one({"email": session["email"]})
    user = User(**user_data)

    todo_data = current_app.db.todo.find({"_id": {"$in": user.todos}})
    todos = [Todo(**todo) for todo in todo_data]

    return render_template(
        "index.html",
        title="Todos App",
        todos_data=todos,
    )


@pages.route("/register", methods=["POST", "GET"])
def register():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = RegisterForm()

    if form.validate_on_submit():
        user = User(
            _id=uuid.uuid4().hex,
            email=form.email.data,
            password=pbkdf2_sha256.hash(form.password.data),
        )

        current_app.db.user.insert_one(asdict(user))

        flash("User registered successfully", "success")

        return redirect(url_for(".login"))

    return render_template(
        "register.html", title="Todos App - Register", form=form
    )


@pages.route("/login", methods=["GET", "POST"])
def login():
    if session.get("email"):
        return redirect(url_for(".index"))

    form = LoginForm()

    if form.validate_on_submit():
        user_data = current_app.db.user.find_one({"email": form.email.data})
        if not user_data:
            flash("Login credentials not correct", category="danger")
            return redirect(url_for(".login"))
        user = User(**user_data)

        if user and pbkdf2_sha256.verify(form.password.data, user.password):
            session["user_id"] = user._id
            session["email"] = user.email

            return redirect(url_for(".index"))

        flash("Login credentials not correct", category="danger")

    return render_template("login.html", title="Todos App - Login", form=form)


@pages.route("/logout")
def logout():
    del session["email"]
    del session["user_id"]

    return redirect(url_for(".login"))


@pages.route("/add", methods=["GET", "POST"])
@login_required
def add_todo():
    form = TodoForm()

    if form.validate_on_submit():
        # print("first",form.due_date.data)
        todo = Todo(
            _id=uuid.uuid4().hex,
            title=form.title.data,
            description=form.description.data,
            due_date=form.due_date.data
            # datetime.datetime.fromisoformat(form.due_date.data)
        )
        current_app.db.todo.insert_one(asdict(todo))

        current_app.db.user.update_one(
            {"_id": session["user_id"]}, {"$push": {"todos": todo._id}}
        )

        return redirect(url_for(".todo", _id=todo._id))

    return render_template(
        "new_todo.html", title="Todos App - Add Todo", form=form
    )


@pages.get("/todo/<string:_id>")
def todo(_id: str):
    todo = Todo(**current_app.db.todo.find_one({"_id": _id}))
    return render_template("todo_details.html", todo=todo)


@pages.route("/edit/<string:_id>", methods=["GET", "POST"])
@login_required
def edit_todo(_id: str):
    todo = Todo(**current_app.db.todo.find_one({"_id": _id}))
    form = TodoForm(obj=todo)
    if form.validate_on_submit():
        todo.title = form.title.data
        todo.description = form.description.data
        todo.due_date = form.due_date.data

        current_app.db.todo.update_one({"_id": todo._id}, {"$set": asdict(todo)})
        return redirect(url_for(".todo", _id=todo._id))
    return render_template("todo_form.html", todo=todo, form=form)

@pages.route("/delete/<string:_id>")
@login_required
def delete_todo(_id:str):
    current_app.db.todo.delete_one({'_id':_id})
    return redirect(url_for(".index"))

@pages.get("/toggle-theme")
def toggle_theme():
    current_theme = session.get("theme")
    if current_theme == "dark":
        session["theme"] = "light"
    else:
        session["theme"] = "dark"

    return redirect(request.args.get("current_page"))

if __name__ == '__main__':
    pages.run(debug=True)

templates/index.html
{% extends "layout.html" %}


{% block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/todos.css') }}" />
{% endblock %}

{% block main_content %}

    {%- if todos_data %}
        <table class="table">
            <colgroup>
                <col style="width: 60%">
                <col style="width: 25%">
                <col style="width: 15%">
            </colgroup>
            <thead>
                <tr class="table__header">
                    <th class="table__cell table__cell--header">Title</th>
                    <th class="table__cell table__cell--header">Due Date</th>
                    <th class="table__cell table__cell--header"></th>
                </tr>
            </thead>
            <tbody>
                {% for todo in todos_data %}
                    <tr>
                        <td class="table__cell">
                            <p class="table__todoTitle">{{ todo.title }}</p>
                            <p class="table__todoDescription">By {{ todo.description }}</p>
                        </td>
                        <td class="table__cell">{{todo.due_date.strftime("%d %b %Y")}}</td>
                        <td class="table__cell"><a href="{{ url_for('pages.todo', _id=todo._id) }}" class="table__link">View</a></td>
                    </tr>
                {% endfor %}
            </tbody>
        </table>
        
    {% else %}
        <p class="table__empty">You haven't added any todos yet. <a href="{{ url_for('pages.add_todo') }}" class="link">Add one!</a></p>
    {% endif %}

    <a href="{{ url_for('pages.add_todo') }}" class="button button--add">
        <span>+</span>
    </a>

{% endblock %}

templates/layout.html
{% from "macros/nav.html" import header %}
{% from "macros/footer.html" import footer %}

<!DOCTYPE html>
<html lang="en"  class="{{ 'dark-mode' if session.get('theme') == 'dark' }}">
    <head>
        <meta charset="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta http-equiv="X-UA-Compatible" content="ie=edge" />
        <title>{{ title | default('TODO APP') }}</title>
        <link href="https://fonts.googleapis.com/css?family=Public+Sans:400,600&display=swap" rel="stylesheet">
        <link rel="stylesheet" href="{{ url_for('static', filename='css/reset.css') }}" />
        <link rel="stylesheet" href="{{ url_for('static', filename='css/main.css') }}" />

        {% block head_content %} {% endblock %}
    </head>
    
    <body>

        {{ header(session.get("email"), session.get("theme")) }}

        <main class="main">
            {% block main_content %} {% endblock %}
        </main>

        {{ footer() }}
    </body>
</html>

templates/login.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %}


{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 


{% block main_content %}

    <form name="login" method="post" novalidate class="form">
        {% with messages = get_flashed_messages(with_categories=true) %}
            {%- for category, message in messages %}
                <span class="form__flash form__flash--{{category}}"> {{ message }}</span>
            {% endfor %}
        {% endwith %}

        <div class="form__container">
            {{ form.hidden_tag() }}
    
            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
    
            <span class="form__small">
                Don't have an account? <a href="{{ url_for('pages.register') }}" class="form__link">Register here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

templates/macros/fields.html
{% macro render_text_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(class_="form__field")}}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}


{% macro render_area_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}
    {{ field(rows=4, class_="form__field", style="resize: none") }}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

{% macro render_date_field(field) %}
<div class="form__group">
    {{ field.label(class_="form__label") }}

    {{ field(class_="form__field") }}

    {%- for error in field.errors %}
        <span class="form__error">{{ error }}</span>
    {% endfor %}
</div>
{% endmacro %}

templates/macros/footer.html
{% macro footer() %}
<footer class="footer">
    <small>Copyright &copy;2022. Todos App. All rights reserved.</small>
</footer>
{% endmacro %}

templates/macros/nav.html
{% from "macros/svgs.jinja2" import moon, sun, todo_icon1, todo_icon2 %}

{% macro header(email, theme) %}
<header class="header">
    <div class="nav-container">
        <a href="{{ url_for('pages.index') }}" class="header__logo">
        
            {{ todo_icon1("logo__icon") }}
            <span class="logo__name">Todo App</span>
        </a>
        <nav class="nav">
            {%- if not email %}
                <a
                    href="{{ url_for('pages.login') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.login') }}"
                >
                    <span class="nav__item">Log in</span>
                </a>
                <a
                    href="{{ url_for('pages.register') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.register') }}"
                >
                    <span class="nav__item">Register</span>
                </a>
            {% else %}
                <a 
                    href="{{ url_for('pages.index') }}"
                    class="nav__link {{ 'nav__link--active' if request.path == url_for('pages.index') }}"
                >
                    <span class="nav__item">Todos</span>
                </a>
                <a
                    href="{{ url_for('pages.logout') }}"
                    class="nav__link"
                >
                    <span class="nav__item">Log out</span>
                </a>
            {% endif %}
            <a
                href="{{ url_for('pages.toggle_theme', current_page=request.path) }}"
                class="nav__link"
            >
                <span class="nav__item">
                    {% if theme == "dark" %}
                        {{ sun("nav__icon") }}
                    {% else %}
                        {{ moon("nav__icon") }}
                    {% endif %}
                </span>
            </a>
        </nav>
    </div>
</header>
{% endmacro %}

templates/new_todo.html
{% from "macros/fields.html" import render_text_field, render_area_field, render_date_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="add_todo" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_area_field(form.description) }}
            {{ render_date_field(form.due_date) }}
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

templates/register.html
{% from "macros/fields.html" import render_text_field %}

{% extends "layout.html" %} 


{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %} 


{% block main_content %}

    <form name="register" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}

            {{ render_text_field(form.email) }}
            {{ render_text_field(form.password) }}
            {{ render_text_field(form.confirm_password) }}
    
            <span class="form__small">
                Already have an account? <a href="{{ url_for('pages.login') }}" class="form__link">Log in here</a>.
            </span>
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}

templates/todo_details.html
{% from "macros/svgs.jinja2" import star, pencil, bin %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/todo_details.css') }}" />
{% endblock %}

{% block main_content %}
<div class="container">
    <header class="todo__header">
        <div class="header__row">
            <div class="todo__name">
                <h1>{{ todo.title }}</h1>
            </div>
            <div class="todo__date">
                {% if todo.due_date %}
                    <p>
                        Due at <time datetime="{{ todo.due_date }}">{{todo.due_date.strftime("%d %b %Y")}}</time>
                    </p>
                {% endif %}
                <a class="todo__edit" href="{{ url_for('pages.edit_todo', _id=todo._id) }}">Edit {{ pencil("pencil") }}</a>
                <a class="todo__delete" href="{{ url_for('pages.delete_todo', _id=todo._id) }}">Delete {{ bin("bin") }}</a>
            </div>
        </div>
    </header>


    {% if todo.description %}
        <p class="todo__description">{{ todo.description }}</p>
    {% else %}
        <p class="todo__description">No description yet. <a class="link" href="{{ url_for('pages.edit_todo', _id=todo._id) }}">Add one?</a></p>
    {% endif %}
    
</div>
{% endblock %}

templates/todo_form.html
{% from "macros/fields.html" import render_text_field, render_area_field, render_date_field %}

{% extends "layout.html" %}

{%- block head_content %}
    <link rel="stylesheet" href="{{ url_for('static', filename='css/forms.css') }}" />
{% endblock %}

{% block main_content %}

    <form name="add_todo" method="post" novalidate class="form">
        <div class="form__container">
            {{ form.hidden_tag() }}
            {{ render_text_field(form.title) }}
            {{ render_area_field(form.description) }}
            {{ render_date_field(form.due_date) }}
    
            <div>
                {{ form.submit(class_="button button--form") }}
            </div>
        </div>
    </form>

{% endblock %}